VERSION = "2.0.0"

YOUTUBE_URL = "https://youtube.com/@mouredev"
TWITCH_URL = "https://youtube.com/@mouredev"
GITHUB_URL = "https://youtube.com/@mouredev"
ADEVIENTO_URL = "https://youtube.com/@mouredev"
MOUREDEV_URL = "https://youtube.com/@mouredev"
TWITTER_URL = "https://youtube.com/@mouredev"
DISCORD_URL = "https://youtube.com/@mouredev"
DISCORD_EVENT_URL = "https://youtube.com/@mouredev"
GITHUB_REPO_URL = "https://youtube.com/@mouredev"